name: data-downloader
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.10.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - beautifulsoup4==4.11.2
      - bs4==0.0.1
      - charset-normalizer==3.1.0
      - dill==0.3.6
      - idna==3.4
      - lxml==4.9.2
      - numpy==1.24.2
      - pandas==1.5.3
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - requests==2.28.2
      - six==1.16.0
      - soupsieve==2.4
      - urllib3==1.26.14
